### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by lighting9999** [adysec/tracker#1]
[merged_merged_trackers_all_http.txt](https://github.com/user-attachments/files/17001718/merged_merged_trackers_all_http.txt)

[trackerlist.txt](https://github.com/user-attachments/files/17001717/trackerlist.txt)
[rw_ws_up_hp_hs_v4_v6.txt](https://github.com/user-attachments/files/17001716/rw_ws_up_hp_hs_v4_v6.txt)
tracker服务器列表，进行合并

**Comment by adysec** [comment]
已合并，感谢提交

**Comment by lighting9999** [comment]
ok
