### ISSUE TITLE
Urgent:There is a formatting error on the tracker

### ISSUE THREAD

**Issue by lighting9999** [adysec/tracker#2]
There is a formatting *error* on the tracker,We have identified the error and corrected the format. It is currently urgent. 
[trackers_all.txt](https://github.com/user-attachments/files/17529595/trackers_all.txt)
[trackers_best.txt](https://github.com/user-attachments/files/17529596/trackers_best.txt)

Replacing the file can solve the problem.

**Comment by adysec** [comment]
Thank you for bringing this issue to my attention. I have already resolved it. However, since this is part of an automated script that runs daily, I have created a bash script to handle any improperly formatted tracker server lists in the future. Your feedback is greatly appreciated.
